export const brand = {
  name: "BST",
  legalName: "BST Business Support Technology Ltd",
  logo: "/bst-logo.jpg",
  tagline: "Websites, performance marketing, and growth systems.",
  whatsapp: process.env.NEXT_PUBLIC_WHATSAPP || "966500000000",
  email: process.env.NEXT_PUBLIC_EMAIL || "hello@growbiz.digital",
};

export const copy = {
  navHome: "Home",
  navProjects: "Work",
  navContact: "Contact",
  navAdmin: "Admin",
  navServices: "Services",
  navReviews: "Reviews",
  menuOpen: "Menu",
  menuClose: "Close",
  headerDescriptor: "Independent digital studio / KSA + BD",
  heroKicker: "Saudi Arabia · Bangladesh",
  heroTitle: "A professional digital presence that wins customers.",
  heroBody:
    "We design conversion-focused websites and run full-funnel digital marketing — paid ads, SEO, social, and WhatsApp automation — so your brand looks credible and generates qualified leads.",
  ctaPrimary: "Request a website",
  ctaSecondary: "View our work",
  offerTitle: "Website package",
  offerPrice: "1,000 SAR",
  offerBody:
    "A professional, modern website with lifetime support. Built to establish trust and convert visitors into inquiries.",
  servicesTitle: "Capabilities",
  servicesIntro: "End-to-end digital marketing and online infrastructure for growing businesses.",
  focusTitle: "Primary focus",
  focusBody:
    "We deliver a polished, customer-ready website that strengthens credibility and creates a reliable channel for new leads.",
  teamTitle: "Cross-border delivery",
  teamBody:
    "Specialists in Saudi Arabia and Bangladesh collaborate on strategy, production, and campaign management — with clear communication and accountable delivery.",
  legalTitle: "Legal support",
  legalBody:
    "Consultation and legal assistance through licensed Bangladeshi advocates, available when your business needs it.",
  projectsTitle: "Existing Projects",
  projectsEmpty: "Portfolio items will appear here once they are published from the admin panel.",
  viewLive: "Visit live site",
  viewDetails: "Case details",
  workTitle: "Recent activity",
  contactTitle: "Start a conversation",
  contactBody:
    "Tell us about your business goals. We will recommend a website, campaign, or growth plan that fits your market.",
  sendWhatsApp: "Message on WhatsApp",
  sendEmail: "Email the team",
  footerNote: "Digital strategy, websites, and paid media across Saudi Arabia and Bangladesh.",
  allCategories: "All",
  featured: "Featured",
  languageLabel: "বাংলা",
  services: [
    "Professional website development — 1,000 SAR",
    "Facebook marketing",
    "YouTube marketing",
    "Instagram marketing",
    "Brand identity and graphic design",
    "Video, Reels, and ad production",
    "SEO and Google Business optimization",
    "Google, Meta, TikTok, and Snapchat ads",
    "WhatsApp marketing and automation",
    "Analytics and monthly reporting",
    "Full digital marketing programs",
    "Google Business Profile setup",
    "Legal support from Bangladeshi advocates",
  ],
} as const;

export const banglaCopy: typeof copy = {
  navHome: "হোম",
  navProjects: "কাজ",
  navContact: "যোগাযোগ",
  navAdmin: "অ্যাডমিন",
  navServices: "সেবাসমূহ",
  navReviews: "রিভিউ",
  menuOpen: "মেনু",
  menuClose: "বন্ধ করুন",
  headerDescriptor: "স্বাধীন ডিজিটাল স্টুডিও / সৌদি আরব + বাংলাদেশ",
  heroKicker: "সৌদি আরব · বাংলাদেশ",
  heroTitle: "এমন পেশাদার ডিজিটাল উপস্থিতি, যা গ্রাহক এনে দেয়।",
  heroBody: "আমরা রূপান্তর-কেন্দ্রিক ওয়েবসাইট তৈরি করি এবং পেইড বিজ্ঞাপন, SEO, সোশ্যাল মিডিয়া ও WhatsApp অটোমেশন পরিচালনা করি, যাতে আপনার ব্র্যান্ড বিশ্বাসযোগ্য হয় এবং মানসম্মত লিড তৈরি করে।",
  ctaPrimary: "ওয়েবসাইটের জন্য যোগাযোগ করুন",
  ctaSecondary: "আমাদের কাজ দেখুন",
  offerTitle: "ওয়েবসাইট প্যাকেজ",
  offerPrice: "১,০০০ SAR",
  offerBody: "আজীবন সহায়তাসহ একটি আধুনিক ও পেশাদার ওয়েবসাইট, যা আস্থা তৈরি করে এবং ভিজিটরকে যোগাযোগে উৎসাহিত করে।",
  servicesTitle: "সেবাসমূহ",
  servicesIntro: "বর্ধনশীল ব্যবসার জন্য সম্পূর্ণ ডিজিটাল মার্কেটিং ও অনলাইন অবকাঠামো।",
  focusTitle: "আমাদের মূল লক্ষ্য",
  focusBody: "আমরা এমন একটি পরিপাটি, গ্রাহক-প্রস্তুত ওয়েবসাইট তৈরি করি, যা বিশ্বাসযোগ্যতা বাড়ায় এবং নতুন লিডের নির্ভরযোগ্য পথ তৈরি করে।",
  teamTitle: "সীমান্ত পেরিয়ে সহযোগিতা",
  teamBody: "সৌদি আরব ও বাংলাদেশের বিশেষজ্ঞরা কৌশল, প্রোডাকশন ও ক্যাম্পেইন পরিচালনায় একসঙ্গে কাজ করেন, স্বচ্ছ যোগাযোগ ও দায়বদ্ধ ডেলিভারির সঙ্গে।",
  legalTitle: "আইনি সহায়তা",
  legalBody: "আপনার ব্যবসার প্রয়োজনে লাইসেন্সপ্রাপ্ত বাংলাদেশি আইনজীবীদের মাধ্যমে পরামর্শ ও আইনি সহায়তা।",
  projectsTitle: "সম্প্রতি সম্পন্ন কাজ",
  projectsEmpty: "অ্যাডমিন প্যানেল থেকে প্রকাশিত হলে পোর্টফোলিও এখানে দেখা যাবে।",
  viewLive: "লাইভ সাইট দেখুন",
  viewDetails: "বিস্তারিত",
  workTitle: "সাম্প্রতিক কার্যক্রম",
  contactTitle: "আলোচনা শুরু করি",
  contactBody: "আপনার ব্যবসার লক্ষ্য সম্পর্কে বলুন। আপনার বাজার অনুযায়ী ওয়েবসাইট, ক্যাম্পেইন বা গ্রোথ প্ল্যান সাজেস্ট করব।",
  sendWhatsApp: "WhatsApp-এ মেসেজ করুন",
  sendEmail: "টিমকে ইমেইল করুন",
  footerNote: "সৌদি আরব ও বাংলাদেশে ডিজিটাল কৌশল, ওয়েবসাইট ও পেইড মিডিয়া।",
  allCategories: "সব",
  featured: "বিশেষ",
  languageLabel: "English",
  services: [
    "পেশাদার ওয়েবসাইট ডেভেলপমেন্ট — ১,০০০ SAR",
    "Facebook মার্কেটিং",
    "YouTube মার্কেটিং",
    "Instagram মার্কেটিং",
    "ব্র্যান্ড আইডেন্টিটি ও গ্রাফিক ডিজাইন",
    "ভিডিও, Reels ও বিজ্ঞাপন তৈরি",
    "SEO ও Google Business অপটিমাইজেশন",
    "Google, Meta, TikTok ও Snapchat বিজ্ঞাপন",
    "WhatsApp মার্কেটিং ও অটোমেশন",
    "অ্যানালিটিক্স ও মাসিক রিপোর্ট",
    "সম্পূর্ণ ডিজিটাল মার্কেটিং প্রোগ্রাম",
    "Google Business Profile সেটআপ",
    "বাংলাদেশি আইনজীবীদের আইনি সহায়তা",
  ],
};

export const arabicCopy: typeof copy = {
  navHome: "الرئيسية",
  navProjects: "أعمالنا",
  navContact: "تواصل معنا",
  navAdmin: "الإدارة",
  navServices: "الخدمات",
  navReviews: "آراء العملاء",
  menuOpen: "القائمة",
  menuClose: "إغلاق",
  headerDescriptor: "استوديو رقمي مستقل / السعودية + بنغلاديش",
  heroKicker: "المملكة العربية السعودية · بنغلاديش",
  heroTitle: "حضور رقمي احترافي يجذب العملاء.",
  heroBody: "نصمم مواقع إلكترونية تركز على التحويل، وندير التسويق الرقمي المتكامل، من الإعلانات المدفوعة وتحسين محركات البحث إلى وسائل التواصل وأتمتة واتساب، لتبدو علامتك موثوقة وتحقق عملاء محتملين مؤهلين.",
  ctaPrimary: "اطلب موقعًا إلكترونيًا",
  ctaSecondary: "شاهد أعمالنا",
  offerTitle: "باقة الموقع الإلكتروني",
  offerPrice: "١٬٠٠٠ ريال",
  offerBody: "موقع إلكتروني احترافي وعصري مع دعم مدى الحياة، مصمم لبناء الثقة وتحويل الزوار إلى استفسارات.",
  servicesTitle: "إمكاناتنا",
  servicesIntro: "تسويق رقمي متكامل وبنية تحتية إلكترونية للشركات النامية.",
  focusTitle: "تركيزنا الأساسي",
  focusBody: "نقدم موقعًا أنيقًا وجاهزًا للعملاء يعزز المصداقية وينشئ قناة موثوقة للحصول على عملاء جدد.",
  teamTitle: "تنفيذ عابر للحدود",
  teamBody: "يتعاون متخصصون في السعودية وبنغلاديش على الاستراتيجية والإنتاج وإدارة الحملات، مع تواصل واضح وتنفيذ مسؤول.",
  legalTitle: "الدعم القانوني",
  legalBody: "استشارات ومساعدة قانونية عبر محامين بنغلاديشيين مرخصين عند حاجة عملك إليها.",
  projectsTitle: "أعمالنا الحالية",
  projectsEmpty: "ستظهر نماذج الأعمال هنا بعد نشرها من لوحة الإدارة.",
  viewLive: "زيارة الموقع",
  viewDetails: "تفاصيل المشروع",
  workTitle: "النشاط الأخير",
  contactTitle: "لنبدأ محادثة",
  contactBody: "أخبرنا عن أهداف عملك، وسنقترح موقعًا أو حملة أو خطة نمو تناسب سوقك.",
  sendWhatsApp: "راسلنا عبر واتساب",
  sendEmail: "راسل الفريق بالبريد",
  footerNote: "استراتيجية رقمية ومواقع وإعلانات مدفوعة في السعودية وبنغلاديش.",
  allCategories: "الكل",
  featured: "مميز",
  languageLabel: "English",
  services: [
    "تطوير موقع احترافي — ١٬٠٠٠ ريال",
    "التسويق عبر فيسبوك",
    "التسويق عبر يوتيوب",
    "التسويق عبر إنستغرام",
    "هوية العلامة التجارية والتصميم الجرافيكي",
    "إنتاج الفيديو والريلز والإعلانات",
    "تحسين محركات البحث وملف النشاط التجاري على Google",
    "إعلانات Google وMeta وTikTok وSnapchat",
    "التسويق عبر واتساب والأتمتة",
    "التحليلات والتقارير الشهرية",
    "برامج التسويق الرقمي المتكاملة",
    "إعداد ملف النشاط التجاري على Google",
    "دعم قانوني من محامين بنغلاديشيين",
  ],
};

export const services = copy.services.map((label, index) => ({
  icon: String(index + 1).padStart(2, "0"),
  label,
}));
